export const dummyProviders = [
  {
    _id: "1",
    profilePicture: "https://via.placeholder.com/100",
    name: "Alice Johnson",
    gender: "Female",
    rating: 5,
    price: 700,
    category: "Maid",
  },
  {
    _id: "2",
    profilePicture: "https://via.placeholder.com/100",
    name: "John Doe",
    gender: "Male",
    rating: 4,
    price: 550,
    category: "Cook",
  },
  {
    _id: "3",
    profilePicture: "https://via.placeholder.com/100",
    name: "Maria Lopez",
    gender: "Female",
    rating: 3,
    price: 300,
    category: "Housekeeper",
  },
  {
    _id: "4",
    profilePicture: "https://via.placeholder.com/100",
    name: "David Smith",
    gender: "Male",
    rating: 4,
    price: 600,
    category: "Back-office worker",
  },
  {
    _id: "5",
    profilePicture: "https://via.placeholder.com/100",
    name: "Sophia Brown",
    gender: "Female",
    rating: 5,
    price: 1200,
    category: "Personal Assistant",
  },
  {
    _id: "6",
    profilePicture: "https://via.placeholder.com/100",
    name: "Michael Garcia",
    gender: "Male",
    rating: 2,
    price: 400,
    category: "Data entry",
  },
  {
    _id: "7",
    profilePicture: "https://via.placeholder.com/100",
    name: "Emily Davis",
    gender: "Female",
    rating: 4,
    price: 500,
    category: "Babysitter",
  },
  {
    _id: "8",
    profilePicture: "https://via.placeholder.com/100",
    name: "Chris Martinez",
    gender: "Male",
    rating: 3,
    price: 750,
    category: "Store assistant",
  },
  {
    _id: "9",
    profilePicture: "https://via.placeholder.com/100",
    name: "Jessica Lee",
    gender: "Female",
    rating: 5,
    price: 900,
    category: "Cook",
  },
  {
    _id: "10",
    profilePicture: "https://via.placeholder.com/100",
    name: "Robert Wilson",
    gender: "Male",
    rating: 4,
    price: 650,
    category: "Maid",
  },
];
